# Generated by Django 3.2 on 2021-10-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='guest',
        ),
    ]
