# Generated by Django 3.2 on 2021-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_visitors_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='guest',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='email1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='name1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='status',
            field=models.CharField(choices=[('inside-building', 'Inside Building'), ('checked-out', 'checked-out'), ('check-in', 'check-in')], max_length=100, null=True),
        ),
    ]
